<#
.SYNOPSIS
This function searches for Azure role assignments by user principal name (UPN) across all subscriptions in a tenant.

.PARAMETER UPN
This parameter specifies the user principal name (UPN) to search for.

.PARAMETER TenantId
This parameter specifies the tenant ID to search for the role assignments. If not specified, the default tenant ID is used.

.OUTPUTS
This function outputs a table with the following columns: SubscriptionName, Role, and SubscriptionId.

.EXAMPLE
Example usage of the code:

    PS> Search-AzureRoleAssignmentByUPN -UPN "" -TenantId ""

.NOTES
Generated by GitHub Copilot and modified by John Wildes
#>


function Search-AzureRoleAssignmentByUPN {
    param (
        [Parameter(Mandatory = $true)]
        [string]$UPN,
        [string]$TenantId
    )

    $subscriptions = Get-AzSubscription -TenantId $TenantId -ErrorAction SilentlyContinue

    $results = @()

    foreach ($subscription in $subscriptions) {
        Write-Progress -Activity "Processing subscriptions" -Status "Subscription: $($subscription.Name)" -PercentComplete (($subscriptions.IndexOf($subscription) + 1) / $subscriptions.Count * 100)

        Set-AzContext -SubscriptionId $subscription.Id -ErrorAction SilentlyContinue

        $roleAssignments = Get-AzRoleAssignment -SignInName $UPN -ErrorAction SilentlyContinue

        if ($roleAssignments) {
            foreach ($roleAssignment in $roleAssignments) {
                $result = [PSCustomObject]@{
                    SubscriptionName = $subscription.Name
                    Role = $roleAssignment.RoleDefinitionName
                    SubscriptionId = $subscription.Id
              }

                $results += $result
            }
        }
    }

    if ($results) {
        return $results | Format-Table
    }
    else {
        return "User role assignment not found"
    }
}
