# This code snippet was generated by GitHub Copilot.
# it is a PowerShell script that splits a CSV file into multiple CSV files.
# The script takes the following parameters:
# - The path of the original CSV file
# - The maximum number of rows per file
#
# The script outputs the results to a CSV file.
#
# Generated by GitHub Copilot
# Edited by: John Wildes
# Date: 23JAN2024
# Version: 1.0.0


# Define the path of the original CSV file
$originalFilePath = "C:\Users\914239\Downloads\GitHubEmailOutputOnly.csv"

# Read the original CSV file
$originalData = Import-Csv -Path $originalFilePath

# Define the maximum number of rows per file
$maxRowsPerFile = 1000

# Calculate the number of files needed
$fileCount = [math]::Ceiling($originalData.Count / $maxRowsPerFile)

# Loop through the original data and create new CSV files
for ($i = 0; $i -lt $fileCount; $i++) {
    # Calculate the start and end index for each file
    $startIndex = $i * $maxRowsPerFile
    $endIndex = [math]::Min(($startIndex + $maxRowsPerFile - 1), ($originalData.Count - 1))

    # Get the rows for the current file
    $rows = $originalData[$startIndex..$endIndex]

    # Create a new CSV file for the current file
    $newFilePath = "C:\Users\914239\Downloads\Splits\EmailList_$i.csv"
    $rows | Export-Csv -Path $newFilePath -NoTypeInformation
}

Write-Host "CSV files created successfully."
