# Import the required module
Import-Module AzureAD

function Search-UserByLastName {
    param(
        [Parameter(Mandatory=$true)]
        [string]$lastName
    )

    # Get users with the last name in their UPN or DisplayName
    $users = Get-AzADUser -SearchString $lastName

    # If users are found
    if($users) {
        # Loop through each user
        foreach($user in $users) {
            # Get the user's details
            $userDetails = Get-AzADUser -ObjectId $user.Id

            # Display the user's details
            $userDetails
        }
    } else {
        Write-Host "No users found with the last name $lastName"
    }
}
<#
.SYNOPSIS
This function searches for Azure role assignments by user principal name (UPN) across all subscriptions in a tenant.

.PARAMETER UPN
This parameter specifies the user principal name (UPN) to search for.

.PARAMETER TenantId
This parameter specifies the tenant ID to search for the role assignments. If not specified, the default tenant ID is used.

.OUTPUTS
This function outputs a table with the following columns: SubscriptionName, Role, and SubscriptionId.

.EXAMPLE
Example usage of the code:

    PS> Search-AzureRoleAssignmentByUPN -UPN "" -TenantId ""

.NOTES
Generated by GitHub Copilot and modified by John Wildes
#>


function Search-AzureRoleAssignmentByUPN {
    param (
        [Parameter(Mandatory = $true)]
        [string]$UPN,
        [Parameter(Mandatory = $true)]
        [string]$TenantId
    )

    $subscriptions = Get-AzSubscription -TenantId $TenantId -ErrorAction SilentlyContinue

    $results = @()

    foreach ($subscription in $subscriptions) {
        Write-Progress -Activity "Processing subscriptions" -Status "Subscription: $($subscription.Name)" -PercentComplete (($subscriptions.IndexOf($subscription) + 1) / $subscriptions.Count * 100)

        $timer = Measure-Command {
            $context = Set-AzContext -SubscriptionId $subscription.Id -ErrorAction SilentlyContinue -WarningAction SilentlyContinue
        }
        $executionTime = $timer.TotalMilliseconds
        $executionTimes += $executionTime

        $assignmentTimer = measure-command {
            $roleAssignments = Get-AzRoleAssignment -SignInName $UPN -ErrorAction SilentlyContinue -WarningAction SilentlyContinue
        }
        $assignmentExecutionTime = $assignmentTimer.TotalMilliseconds
        $assignmentExecutionTimes += $assignmentExecutionTime

        if ($roleAssignments) {
            foreach ($roleAssignment in $roleAssignments) {
                $result = [PSCustomObject]@{
                    SubscriptionName = $subscription.Name
                    Role = $roleAssignment.RoleDefinitionName
                    SubscriptionId = $subscription.Id
              }

                $results += $result
            }
        }
    }
    # Write-Host $assignmentExecutionTimes | Measure-Object -Average
    # Write-Host $executionTimes | Measure-Object -Average

    if ($results) {
        return $results | Format-Table

    }
    else {
        return "User role assignment not found" 
    }

}